### ISSUE TITLE
possibly modify the bot to be publicly available and usable

### ISSUE THREAD

**Issue by LeMoonStar** [TrojanerHD/AdventofCode-Bot#10]
Since we probably aren't the only ones using Discord for communication about Advent of Code, it might be appreciated by some people if we make the bot publicly accessible and configurable on a server to server base.
this would require the following changes:
- Being able to save data (AoC session, AoC leaderboard ID) on a server to server basis (should be pretty easy)
- adding a simple command interface so server owners can set the session and the leaderboard ID (or maybe a configuration website using discord login to authenticate, which is considerably harder but probably more secure and easier to use) (should be pretty simple as well)
- modifying the current ChannelUpdater and Leaderboard classes to support multiple servers and configurations. (this again, should be pretty simple)

**Comment by LeMoonStar** [comment]
we should also probably create a milestone for this (after creating the respected issues)

**Comment by TrojanerHD** [comment]
https://github.com/TrojanerHD/AdventofCode-Bot/projects/1

**Comment by TrojanerHD** [comment]
Issue has been split into
+ https://github.com/TrojanerHD/AdventofCode-Bot/issues/12
+ https://github.com/TrojanerHD/AdventofCode-Bot/issues/13
+ https://github.com/TrojanerHD/AdventofCode-Bot/issues/14
