### ISSUE TITLE
missing complete prettier.io configuration

### ISSUE THREAD

**Issue by LeMoonStar** [TrojanerHD/AdventofCode-Bot#11]
as the [CONTRIBUTING.md](https://www.github.com/TrojanerHD/AdventofCode-Bot/tree/main/CONTRIBUTING.md) file states, the prettier.io code formatter is used, but when looking into the current config, only the singleQuote option is set.
Now that there are formatting rules specified (inside the CONTRIBUTING.md file) these should be also applied to the prettier.io configuration.

**Comment by TrojanerHD** [comment]
As far as I can tell the default options of prettier are matching with my [CONTRIBUTING.md](https://www.github.com/TrojanerHD/AdventofCode-Bot/tree/main/CONTRIBUTING.md) — correct me if I am wrong

**Comment by LeMoonStar** [comment]
> As far as I can tell the default options of prettier are matching with my [CONTRIBUTING.md](https://www.github.com/TrojanerHD/AdventofCode-Bot/tree/main/CONTRIBUTING.md) — correct me if I am wrong

I never used prettier.io before, never even heard of it, until now I only used unrustify. but yes, after formatting one file with it, I noticed that prettier.io does use a default configuration, I don't know if it fits to the CONTRIBUTING.md file, but I think that'd be a different issue.
