### ISSUE TITLE
Differentiate data (AoC session, AoC leaderboard ID) on a server to server basis

### ISSUE THREAD

**Issue by TrojanerHD** [TrojanerHD/AdventofCode-Bot#12]
https://github.com/TrojanerHD/AdventofCode-Bot/issues/10

**Comment by LeMoonStar** [comment]
should the data be stored in JSON or SQLite (or any other specific database?)

**Comment by TrojanerHD** [comment]
It would be good to know the data is safe since the you can delete ones account with the session cookie but other than that it doesn't really matter to me

**Comment by LeMoonStar** [comment]
> It would be good to know the data is safe since the you can delete ones account with the session cookie but other than that it doesn't really matter to me

SQLite is basically just a file, but access to it is via SQL and all in all it is better suited for this kind of usage. It is just as save as a JSON file if you can make sure no one can access the file it is save.

**Comment by TrojanerHD** [comment]
We will go with SQLite then

**Comment by LeMoonStar** [comment]
this issue should be closed... seems like the issue - PR linking doesn't really work

**Comment by TrojanerHD** [comment]
Continued in #22
