### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by LeMoonStar** [TrojanerHD/AdventofCode-Bot#15]
every project should have a license, not just to protect yourself and the contributors legally, but also to tell people what they are allowed and not allowed with the project.

keep in mind that every contributor has to accept changes to the license (and thus also the addition of a license) because part of the code belongs to them.

**Comment by TrojanerHD** [comment]
Any license recommendations? Anything speaking against the [WTFPL](http://www.wtfpl.net/) license?

**Comment by LeMoonStar** [comment]
> Any license recommendations? Anything speaking against the [WTFPL](http://www.wtfpl.net/) license?

I am a huge fan of the MIT license, I don't think the WTFPL is a really good choise, cause it doesn't state that there is no guarantee and no warranty, it also isn't really professional, is it?

**Comment by TrojanerHD** [comment]
@LeMoonStar @joblo2213 Do you, as current contributors to this project, agree on changing the license of this repository (https://github.com/TrojanerHD/AdventofCode-Bot) to the MIT license as stated in https://choosealicense.com/licenses/mit/?

**Comment by LeMoonStar** [comment]
> @LeMoonStar @joblo2213 Do you, as current contributors to this project, agree on changing the license of this repository (https://github.com/TrojanerHD/AdventofCode-Bot) to the MIT license as stated in https://choosealicense.com/licenses/mit/?

yes, I agree to the use of the MIT license for this project.

**Comment by joblo2213** [comment]
MIT all the way 💯
