### ISSUE TITLE
Stars for completing a day in under 3 hours doesn't work

### ISSUE THREAD

**Issue by LeMoonStar** [TrojanerHD/AdventofCode-Bot#23]
The feature to show different stars depending on different conditions which was introduced in PR #8 also added an ✨ emoji when the Day was completed in under 3 hours. but since some time the emoji doesn't work anymore and instead a normal ⭐ is shown, though it did work when it was merged. The problem was first noticed yesterday ( 2020-12-11 ) but may have been unnoticed for longer.

Since PR #19 hasn't changed anything which is currently implemented and only added a file and a dependency we can be pretty sure this is not the cause.

**Comment by daanbreur** [comment]
It may be a calculation error or something

**Comment by LeMoonStar** [comment]
at first I thought it could be this commit: 3cc00f06130e82ea7486e02b69e8eb2f5a0b8648 , since it moved the function to get the Date object of the beginning of the challenge into the new common.ts file, so both Leaderboard.ts and ChannelUpdater.ts share the function and don't have to have their own implementation of it. But when looking at it, the common.ts file is imported, but not used, - or im just blind. the only changes in the Leaderboard file are formatting changes... so maybe it is not this commit... tough it seemed most likely at first.

**Comment by daanbreur** [comment]
That's the issue then I think 😆
