### ISSUE TITLE
Automatically/Dynamically propagate day channels into category of choice.

### ISSUE THREAD

**Issue by daanbreur** [TrojanerHD/AdventofCode-Bot#26]
Automatically make the channels in a category.
Category can be set using the command interface, In which channels with name `{year}-{day}` will be made
- #13

**Comment by LeMoonStar** [comment]
Note that #14 requests for the category name pattern and the channel name pattern to be configurable from a server to server basis and #19 added a database helper helping to save this data.
It was planned for the current draft pull request #24 to apply the saved data, however, I kinda got off track there and currently have lots to do. Thus I don't think i'll implement that any time soon. When this is implemented, the only thing missing is a command line interface as requested in #13.

**Comment by daanbreur** [comment]
yup, I saw that!
so the channel name pattern could be used for creation instead of moving?

**Comment by LeMoonStar** [comment]
> yup, I saw that!
> so the channel name pattern could be used for creation instead of moving?

In my opinion yes, and while working on #24 I asked @TrojanerHD if it is ok to change that, as far as I remember they were ok with it. They might however prefer it the current way, which I personally think isn't really user-friendly.

**Comment by daanbreur** [comment]
Im gonna change it locally. To which branch should I PR?

**Comment by LeMoonStar** [comment]
> To which branch should I PR?
You should generally PR into the unstable branch

**Comment by daanbreur** [comment]
Alright

**Comment by LeMoonStar** [comment]
May I ask what exactly you're going to change now?

**Comment by daanbreur** [comment]
Automatically making the channels instead of moving them.

**Comment by daanbreur** [comment]
#28
