### ISSUE TITLE
The leaderboard needs a legend or something similar

### ISSUE THREAD

**Issue by TrojanerHD** [TrojanerHD/AdventofCode-Bot#9]
The different types of stars in the #leaderboard-Channel are confusing for everyone who does not know for what they stand — a legend or some other kind of explanation is required somewhere

**Comment by LeMoonStar** [comment]
If you don't want to do it, I'd do it tomorrow

**Comment by daanbreur** [comment]
I will do it if you want to! But i never coded in Typescript

**Comment by LeMoonStar** [comment]
> I will do it if you want to! But i never coded in Typescript

it's already assigned to me. code is ready just needs testing and committing

**Comment by daanbreur** [comment]
oh okey

**Comment by LeMoonStar** [comment]
added with #16
